name: portfolio

services:
  postgres:
    container_name: postgres
    image: postgres-15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgres/data/

volumes:
  postgres_data:
